export const GET_POKEMON = "GET_POKEMON";
// export const ADD_POKEMON = "ADD_POKEMON";
// export const DELETE_POKEMON = "DELETE_POKEMON";
// export const UPDATE_POKEMON = "UPDATE_POKEMON";
// export const GET_FILTER_POKEMONS = "GET_FILTER_POKEMONS";
