export const GET_TEMPLATES = "GET_TEMPLATES";
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const UPDATE_TEMPLATE = "UPDATE_TEMPLATE";
export const GET_FILTER_TEMPLATES = "GET_FILTER_TEMPLATES";
